config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users
  resources :projects
  resources :collaborates
  resources :follows
  
get 'projects/:id/join' => 'projects#join'
get 'projects/:id/follow' => 'projects#follow'

end

app/models/collaborates.rb
class Collaborates < ActiveRecord::Base
	belongs_to :user
	belongs_to :project


end

app/models/comments_on.rb
class CommentsOn < ActiveRecord::Base
	belongs_to :users
	belongs_to :projects
end

app/models/follows.rb
class Follows < ActiveRecord::Base
	belongs_to :users
	belongs_to :projects
end

app/models/has_skills.rb
class HasSkill < ActiveRecord::Base
	belongs_to :users
	belongs_to :skills
end

app/models/has_tags.rb
class HasTags < ActiveRecord::Base
	belongs_to :tags
	belongs_to :projects
end

app/models/is_colleague_of.rb
class IsColleagueOf < ActiveRecord::Base
	belongs_to :users
end

app/models/message.rb
class Message < ActiveRecord::Base
	has_many :sends
	has_many :users, :through => :sends
end

app/models/project.rb
class Project < ActiveRecord::Base

	has_many :tasks
	accepts_nested_attributes_for :tasks,:allow_destroy => true

mount_uploader :propic, PropicUploader


	has_many :comments_on
	has_many :users, :through => :comments_on

	has_many :collaborates
	has_many :users, :through => :collaborates

	has_many :follows
	has_many :users, :through => :follows

	has_many :requires_skill
	has_many :skills, :through => :requires_skill

	has_many :has_tags
	has_many :tags, :through => :has_tags



	 

end

app/models/requires_skills.rb
class RequiresSkill < ActiveRecord::Base
	belongs_to :skills
	belongs_to :projects
end

app/models/sends.rb
class Sends < ActiveRecord::Base
	belongs_to :users
	belongs_to :messages
end

app/models/skill.rb
class Skill < ActiveRecord::Base

	has_many :has_skill
	has_many :users, :through => :has_skill

	has_many :requires_skill
	has_many :projects, :through => :requires_skill
end

app/models/tag.rb
class Tags < ActiveRecord::Base

	has_many :has_tags
	has_many :projects, :through => :has_tags
end

app/models/task.rb
class Task < ActiveRecord::Base

	has_many :works_on
	has_many :users, :through => :works_on

	belongs_to :projects
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


	

	mount_uploader :avatar, AvatarUploader


# app/views/users/_form.html.erb

	def self.search(search)
  		if search
    		self.where('name like ?', "%#{search}%")
  		else
    		self.all
  		end
	end

	has_many :sends
	has_many :messages, :through => :sends

	has_many :is_colleague_of
	has_many :users, :through => :is_colleague_of

	has_many :works_on
	has_many :tasks, :through => :works_on

	has_many :comments_on
	has_many :projects, :through => :comments_on

	has_many :collaborates
	has_many :projects, :through => :collaborates

	has_many :follows
	has_many :projects, :through => :follows

	has_many :has_skill
	has_many :skills, :through => :has_skill


scope :alphasort, lambda { order("users.first_name ASC") }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/models/works_on.rb
class WorksOn < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 

 
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  respond_to :html
  before_action :set_project, only: [:show, :edit, :update, :destroy, :join]
  before_action :set_creator, only: [:show, :edit, :update]
  before_filter :authenticate_user!, :except => [:index, :show]

  def index
    @projects = Project.find_by_sql "SELECT *
    FROM projects;"

    respond_with(@projects)
  end

  def show
    @tasks = Task.find_by_sql "SELECT *
    FROM tasks, works_on
    WHERE tasks.tid=works_on.tid
    AND tasks.project_id="+params[:id].to_s
    respond_with(@project)
  end

  def new
    @project = Project.new
    respond_with(@project)
  end

  def edit
    respond_with(@project)
  end

  def create
    @project = Project.new(project_params)
    flash[:notice] = 'Project was successfully created.' if @project.save
    respond_with(@project)
  end

  def update
    flash[:notice] = 'Project was successfully updated.' if @project.update(project_params)
    respond_with(@project)
  end

  def destroy
    @project= Project.delete_all("id="+params[:id].to_s)
redirect_to action: 'index'
end

  def delete
    @project= Project.delete_all("id="+params[:id].to_s)
    redirect_to "/index"
  end

  def join
  project = Project.find(params[:id])
   @connection = ActiveRecord::Base.connection
    result = @connection.exec_query('INSERT INTO collaborates VALUES('+current_user.id.to_s+','+project.id.to_s+");")
    redirect_to action: 'show'
     
   
end

def follow
  project = Project.find(params[:id])
   @connection = ActiveRecord::Base.connection
    result = @connection.exec_query('INSERT INTO follows VALUES('+current_user.id.to_s+','+project.id.to_s+");")
    redirect_to action: 'show'


  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def set_creator
      @creator = User.find(@project.creator_id)
    end

    def project_params
      params.require(:project).permit(:creator_id, :name, :description,:slogan,:git,:link, :propic, tasks_attributes:[:id, :task_name,:description, :_destroy])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
  private
 
  def sign_up_params
    params.require(:user).permit(:name, :last_name, :email, :password, :password_confirmation)
  end
 
  def account_update_params
    params.require(:user).permit(:name, :last_name, :email, :password, :password_confirmation, :current_password , :website, :facebook, :twitter, :linkedin, :github, :location, :interest, :works_in, :info ,:avatar)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
 
  def index
    @users = User.search(params[:search])
  end

  def show
    @user = User.find(params[:id])
    @projects = Project.find_by_sql "SELECT * FROM projects WHERE creator_id="+params[:id].to_s
    @i_follow = Follows.find_by_sql "SELECT * FROM follows WHERE uid="+params[:id].to_s
    @collaborates = Collaborates.find_by_sql "SELECT * FROM collaborates WHERE user_id="+params[:id].to_s
    @following_me = Follows.find_by_sql "SELECT * FROM follows, projects WHERE follows.pid=projects.id AND creator_id="+params[:id].to_s
  end

  def edit
  	@user = User.find(params[:id])
  end

  def new
    @user = User.new
    
  end


 def update 

    account_update_params = devise_parameter_sanitizer.sanitize(:account_update)
    # For Rails 3
    # account_update_params = params[:user]

    # required for settings form to submit when password is left blank
    if account_update_params[:password].blank?
      account_update_params.delete("password")
      account_update_params.delete("password_confirmation")
    end


  @user = User.find( params[:id])
  if @user.update_attributes(account_update_params)
    sign_in @user, :bypass => true
    respond_with(@user)
  else
    render('edit')
  end
end

private
  
  def user_params
    params.require(:user).permit(:name, :last_name, :email, :website, :facebook, :twitter, :linkedin, :github, :location, :interest, :work_in, :info, :avatar )
  end
  

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%=f.hidden_field :creator_id, :value => current_user.id%>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

   


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_index.html.erb
<div class = "container">
<h1>Projects</h1>


    <% @projects.each do |project| %>
     <div >
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <img id="avatar" class="editable img-responsive" alt="profile pic" src= <%=asset_path('profile-pic.jpg')%> >
      <div class="caption">
        <h3><%= link_to project.name, project %></h3>
        <p>Description: <%= project.description%> </p>
      </div>
    </div>
  </div>
</div>
<%end%>
<br>
<%= link_to 'New Project', new_project_path %>
</div>

app/views/projects/_task_index.html.erb
<% if current_user.id == @creator.id %>
<%= nested_form_for @projects do |f| %>

<%= f.fields_for :tasks do |task_form| %>
  <%= task_form.text_field :task_name %>
  <%= task_form.link_to_remove "Remove this task" %>
<% end %>
<p><%= f.link_to_add "Add a task", :tasks %></p>
<% end %>


<%= link_to 'New Task', '../task/new' %>
<% end %>
<table class="table table-hover">
<tr>
<th>Task</th><th>User</th>
</tr>

  <% @tasks.each do |task| %>
  <tr>
  <td>task.task_name</td><td>task.uid</td>
  </tr>
  <%end%>
</table>

app/views/projects/edit.html.erb
<h1>Editing project</h1>


<%= nested_form_for(@project) do |f| %>
<legend>Avatar</legend>
<%= f.file_field :propic %>

<form role="form">
	<div class="form-group">
		<label for="exampleInputEmail1">Description</label>
		<span class="editable" id="description"> <%= f.text_area :description %> </span>
	</div>
	<div class="form-group">
		<label for="exampleInputEmail1">Slogan</label>
		<span class="editable" id="description"> <%= f.text_field :slogan %> </span>
	</div>
	<div class="form-group">
		<label for="exampleInputEmail1">Project Link</label>
		<span class="editable" id="description"> <%= f.text_field :link %> </span>
	</div>
	<div class="form-group">
		<label for="exampleInputEmail1">GitHub link Link</label>
		<span class="editable" id="description"> <%= f.text_field :git %> </span>
	</div>

	<div class="thing">
    <%= f.fields_for :tasks do |task_form| %>
  <%= task_form.text_field :task_name %>
<%= task_form.text_field :description %>
  <%= task_form.link_to_remove "Remove this task" %>
<% end %>
<p><%= f.link_to_add "Add a task", :tasks %></p>
  </div>
  
	<%= f.submit 'Update', :class => 'button left' %>
	<% end %>
</form>

app/views/projects/index.html.erb
<div class = "container">
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Creator</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.creator_id %></td>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>


<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<!-- WHAT DO? -->
<script type="text/javascript">
  $(document).ready(function(){ 
    $("#myTab a").click(function(e){
      e.preventDefault();
      $(this).tab('show');
    });
  });
</script>




<div class="jumbotron col-md-6">
  <!-- Image on the left -->
  <div class= "project-pic col-md-6" >
    <span class="profile-picture">
                        <% unless @project.propic_url.nil? %><%= image_tag @project.propic_url(:display) %><br />
                        <% else %> <img id="avatar" class="editable img-responsive" alt="profile pic" src= <%=asset_path('project.gif')%> >
                        <% end %> 
                      </span>
  </div>
  <!-- Info on the right -->
  <div class= "project-pic col-md-6" >
    <h3><%= @project.name %> </h3>
    <em><%= @project.slogan %></em>
    <br>
    <ol class="breadcrumb">
      <li><i class="ace-icon fa  fa-eye "></i> X </li><!-- Query for views goes here (?) -->
      <li><i class="ace-icon fa  fa-comment "></i> X </li><!-- Query on comments_on goes here -->
      <li><i class="glyphicon glyphicon-user "></i> X </li><!-- Query on contributors goes here -->
    </ol> 
    
    <p><strong>Author: </strong><%= link_to @creator.name, @creator if @creator %></p>

    <!-- Buttons that depend on user id -->
    <%if current_user.blank? %>
    <!-- Show nothing -->
    <%else%>
    <!-- Check if you're logged in or not -->
    <% if current_user.id == @creator.id %>
    <table>
      <tr>
        <td><%=button_to "Edit",{:controller => "projects", :action => :edit}, :class => "btn btn-success btn-lg", :method => :get%></td>
        <td><%=button_to "Delete", {:controller => "projects", :action => :destroy},:class => "btn btn-danger btn-lg",:method => :delete%></td>
      </tr>
    </table>
    <% else %>
    <table>
      <tr>
        <td><%=button_to "Join",{:controller => "projects", :action => :join}, :class => "btn btn-success btn-lg", :method => :get%></td>
        <td><%=button_to "Follow",{:controller => "projects", :action => :follow}, :class => "btn btn-primary btn-lg", :method => :get%></td>
      </tr>
    </table>
    <% end %>
    <%end%>
  </div>
</div>
<!-- Tabbed content -->
<div class = "col-md-6">
  <ul class="nav nav-tabs" id="myTab">
    <li class="active"><a href="#overview">Overview</a></li>
    <li><a href="#sectionB">Requirements</a></li>
    <li><a href="#sectionC">Tasks</a></li>
    <li><a href="#sectionD">Contributors</a></li>
    <li><a href="#sectionE">Followers</a></li>
  </ul>

  <div class="tab-content">

    <div id="overview" class="tab-pane fade in active">
      <h3>Description</h3>
      <p><%= @project.description %></p>
    </div>

    <div id="sectionB" class="tab-pane fade">
      <h3>Requirements</h3>
      <p>Query for requires tasks goes here</p>
    </div>

    <div id="sectionC" class="tab-pane fade">
      <h3>Tasks</h3>
      <p><%  @connection = ActiveRecord::Base.connection %>
        <% result = @connection.exec_query('select task_name, description from tasks where tasks.project_id ='+ @project.id.to_s+';') %>
        <table class="table table-striped">
        <thead><tr><td>Task</td><td>Description</td></tr></thead>
        <tbody>
          <% result.each do |row| %>
          <tr><td><%= row["task_name"] %></td> <td> <%=row["description"] %></td></tr>
          <% end %>
          </tbody>
        </table>
      </p>
      
    </div>

    <div id="sectionD" class="tab-pane fade">
      <h3>Contributors</h3>
      <p><%  @connection = ActiveRecord::Base.connection %>
        <% result = @connection.exec_query('select name, last_name, users.id from users, collaborates where users.id = collaborates.user_id and collaborates.project_id ='+ @project.id.to_s+';') %>
        <table>
          <% result.each do |row| %>
          <tr><td><%= link_to row["name"]+" "+row["last_name"], User.find(row["id"]) %></td></tr>
          <% end %>
        </table>
      </p>
    </div>

    <div id="sectionE" class="tab-pane fade">
      <h3>Followers</h3>
      <p><%  @connection = ActiveRecord::Base.connection %>
        <% result = @connection.exec_query('select name, last_name, users.id from users, follows where users.id = follows.uid and follows.pid ='+ @project.id.to_s+';') %>
        <table>
          <% result.each do |row| %>
          <tr><td><%= link_to row["name"]+" "+row["last_name"], User.find(row["id"]) %></td></tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>

  <% if @project.git != nil %>
  <div class= "col-md-6">
    <h3>GitHub Repository</h3> 
    <a href=<%=@project.git.to_s%>><%= @project.git.to_s%></a>     
  </div>
  <% end %>

  <% if @project.link != nil %>
  <div class= "col-md-6">
    <h3>Project Link</h3> 
    <a href=<%=@project.link.to_s%>><%= @project.link.to_s%></a>     
  </div>
  <% end %>

app/views/projects/show_old.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Creator:</strong>
  <%= @project.creator_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/users/_index.html.erb
<div class="container">

    <h3>Users</h3>

    <% @users.each do |user| %>

    <%= render user %>
    <% end %>
  
</div>

app/views/users/_user.html.erb
<div >
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
    	<% if user.avatar_url.nil? %>
			<img id="avatar" class="user_index_image" alt="profile pic" src= <%=asset_path('profile-pic.jpg')%> >
		<%else%>
    	<%= image_tag user.avatar_url(:display) %><br />
    	<% end %>

      
      <div class="caption">
        <h3><%= link_to user.name+" "+user.last_name, user %></h3>
        <p>Field of Work: <%= user.works_in%> </p>
      </div>
    </div>
  </div>
</div>


<!--if user.name.nil? then user.name elsif ¨Noname¨+" "+if user.last_name.nil? then user.last_name elsif ¨Noname¨-->

app/views/users/edit.html.erb
 <div>
 	<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put, :role => 'form'}) do |f| %>
 	<%= devise_error_messages! %>
 	<div id="user-profile-1" class="user-profile row">




 		<!-- #section:pages/profile.contact -->


 		


 		<!-- /section:custom/extra.grid -->

 		

 		<div class="col-md-4">


 			<div class="space-12"></div>

 			<!-- Namw-->
 			<h4 class="blue">
 				<span class="middle"> <%= @user.name %> <%= @user.last_name %> 

 				</span>

 			</h4>





 			<!-- #section:pages/profile.info -->
 			<div class="profile-user-info profile-user-info-striped">
 				<div class="profile-info-row">
 					<div class="profile-info-name">First Name </div>

 					<div class="profile-info-value">
 						<span class="editable" id="username"> <%= f.text_field :name %> </span>
 					</div>
 				</div>

 				<div class="profile-info-row">
 					<div class="profile-info-name">Last Name </div>

 					<div class="profile-info-value">
 						<span class="editable" id="username"> <%= f.text_field :last_name %> </span>
 					</div>
 				</div>

 				<div class="profile-info-row email_form">
 					<div class="profile-info-name">Email </div>

 					<div class="profile-info-value">
 						<span class="editable" id="email_form">  <%= f.email_field :email %> </span>
 						<% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
 						<div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
 						<% end %>
 						
 					</div>
 				</div>

 				<div class="profile-info-row">
 					<div class="profile-info-name"> Location </div>

 					<div class="profile-info-value">

 						<span class="editable" id="country"><%= f.text_field :location %></span>
 					</div>
 				</div>







 				<div class="profile-info-row">
 					<div class="profile-info-name"> Interest </div>

 					<div class="profile-info-value">
 						<span class="editable" id="about"><%= f.text_field :interest %></span>
 					</div>
 				</div>

 				<div class="profile-info-row">
 					<div class="profile-info-name"> Field of Work </div>

 					<div class="profile-info-value">
 						<span class="editable" id="about"><%= f.text_field :works_in %></span>
 					</div>
 				</div>
 			</div>
 		</div>


 		<div class="col-md-4">


 			<div class="space-12"></div>

 			<!-- Namw-->
 			<h4 class="blue">
 				<span class="middle"> Websites

 				</span>

 			</h4>





 			<!-- #section:pages/profile.info -->
 			<div class="profile-user-info profile-user-info-striped">
 				<div class="profile-info-row">
 					<div class="profile-info-name">Personal</div>

 					<div class="profile-info-value">
 						<i class="middle ace-icon fa fa-globe fa-2x blue"></i>
 						<span class="editable" id="username"> <%= f.text_field :website %> </span>
 					</div>
 				</div>

 				<div class="profile-info-row">
 					<div class="profile-info-name">Facebook </div>

 					<div class="profile-info-value">
 						<i class="middle ace-icon fa fa-facebook-square fa-2x blue"></i>
 						<span class="editable" id="username"> <%= f.text_field :facebook %> </span>
 					</div>
 				</div>

 				<div class="profile-info-row">
 					<div class="profile-info-name">Twitter </div>

 					<div class="profile-info-value">
 						<i class="middle ace-icon fa fa-twitter-square fa-2x light-blue"></i>
 						<span class="editable" id="username"> <%= f.text_field :twitter %> </span>
 					</div>
 				</div>

 				<div class="profile-info-row">
 					<div class="profile-info-name"> LinkedIn </div>

 					<div class="profile-info-value">
 						<i class="middle ace-icon fa fa-linkedin-square fa-2x red"></i>

 						<span class="editable" id="country"><%= f.text_field :linkedin %></span>
 					</div>
 				</div>

 				<div class="profile-info-row">
 					<div class="profile-info-name"> GitHub </div>

 					<div class="profile-info-value">
 						<i class="middle ace-icon fa fa-github-square fa-2x black"></i>

 						<span class="editable" id="country"><%= f.text_field :github %></span>
 					</div>
 				</div>
 			</div>
 		</div>


 		<div class="col-md-4">


 			<div class="space-12"></div>

 			<!-- Namw-->
 			<h4 class="blue">
 				<span class="middle"> Change Password

 				</span>

 			</h4>





 			<!-- #section:pages/profile.info -->
 			<div class="profile-user-info profile-user-info-striped">
 				<fieldset>
 					<p>Leave these fields blank if you don't want to change your password.</p>
 					<div class="profile-info-row">
 						<div class="profile-info-name">Password</div>

 						<div class="profile-info-value">

 							<span class="editable" id="password"> <%= f.password_field :password, :autocomplete => 'off', class: 'form-control' %> </span>
 						</div>
 					</div>

 					<div class="profile-info-row">
 						<div class="profile-info-name"> Confirmation </div>

 						<div class="profile-info-value">

 							<span class="editable" id="username"> <%= f.password_field :password_confirmation, class: 'form-control' %> </span>
 						</div>
 					</div>
 				</fieldset>
 				<fieldset>
 					<p>You must enter your current password to make changes.</p>
 					<div class="profile-info-row">
 						<div class="profile-info-name"> Current</div>

 						<div class="profile-info-value">

 							<span class="editable" id="username"> <%= f.password_field :current_password, class: 'form-control' %> </span>
 						</div>
 					</div>
 				</fieldset>

 				
 			</div>
 		</div>
 	</div>
 </div>






 <div class="space-20"></div>

 <div class="row">
 	<div class="col-xs-12 col-sm-6">
 		<div class="widget-box transparent">
 			<div class="widget-header widget-header-small">
 				<h4 class="widget-title smaller">
 					<i class="ace-icon fa fa-check-square-o bigger-110"></i>
 					Little About Me
 				</h4>
 			</div>

 			<div class="widget-body">
 				<div class="widget-main">
 					<p>
 						<%= f.text_area :info, :size => "50x10" %>
 					</p>

 				</div>
 			</div>
 		</div>
 	</div>

 	<div class="col-xs-12 col-sm-6">
 		<div class="widget-box transparent">
 			<div class="widget-header widget-header-small header-color-blue2">
 				<h4 class="widget-title smaller">
 					<i class="ace-icon fa fa-lightbulb-o bigger-120"></i>
 					My Skills
 				</h4>
 			</div>

 			<div class="widget-body">
 				<div class="widget-main padding-16">
 					<div class="clearfix">
 						<div class="grid3 center">
 							<!-- #section:plugins/charts.easypiechart -->
 							<div class="easy-pie-chart percentage" data-percent="45" data-color="#CA5952">
 								<span class="percent">45</span>%
 							</div>

 							<!-- /section:plugins/charts.easypiechart -->
 							<div class="space-2"></div>
 							Graphic Design
 						</div>

 						<div class="grid3 center">
 							<div class="center easy-pie-chart percentage" data-percent="90" data-color="#59A84B">
 								<span class="percent">90</span>%
 							</div>

 							<div class="space-2"></div>
 							HTML5 & CSS3
 						</div>

 						<div class="grid3 center">
 							<div class="center easy-pie-chart percentage" data-percent="80" data-color="#9585BF">
 								<span class="percent">80</span>%
 							</div>

 							<div class="space-2"></div>
 							Javascript/jQuery
 						</div>
 					</div>

 					<div class="hr hr-16"></div>

 					<!-- #section:pages/profile.skill-progress -->
 					<div class="profile-skills">
 						<div class="progress">
 							<div class="progress-bar" style="width:80%">
 								<span class="pull-left">HTML5 & CSS3</span>
 								<span class="pull-right">80%</span>
 							</div>
 						</div>

 						<div class="progress">
 							<div class="progress-bar progress-bar-success" style="width:72%">
 								<span class="pull-left">Javascript & jQuery</span>

 								<span class="pull-right">72%</span>
 							</div>
 						</div>

 						<div class="progress">
 							<div class="progress-bar progress-bar-purple" style="width:70%">
 								<span class="pull-left">PHP & MySQL</span>

 								<span class="pull-right">70%</span>
 							</div>
 						</div>

 						<div class="progress">
 							<div class="progress-bar progress-bar-warning" style="width:50%">
 								<span class="pull-left">Wordpress</span>

 								<span class="pull-right">50%</span>
 							</div>
 						</div>

 						<div class="progress">
 							<div class="progress-bar progress-bar-danger" style="width:38%">
 								<span class="pull-left">Photoshop</span>

 								<span class="pull-right">38%</span>
 							</div>
 						</div>
 					</div>

 					<!-- /section:pages/profile.skill-progress -->
 				</div>
 			</div>
 		</div>


 	</div>
 	<%= f.submit 'Update', :class => 'button right' %>
 	<% end %>


 </div>

 
 <div class="authform">
 	<h3>Cancel Account</h3>
 	<p>Unhappy? We'll be sad to see you go.</p>
 	<p>Ablublu</p>

app/views/users/index.html.erb
<div class="container">

	

	<div></div>
	
	<h3>Users</h3>
	<div class= "floatdude">
		<%= form_tag users_path, :method => 'get' do %>
		<%= text_field_tag :search, params[:search], :id => 'search_field' %>
		<%= submit_tag "Search", :name => nil %> 
		
		<% end %>
	</div>
	<div class="dropdown floatdude">
		<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
			Sort
			<span class="caret"></span>
		</button>
		<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
			<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Newest-Oldest</a></li>
			<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Oldest-Newest</a></li>
			<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Alphabetical</a></li>
			
		</ul>
	</div>

</div>






<% @users.each do |user| %>

<%= render user %>
<% end %>

</div>