config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users
  resources :projects
  resources :collaborates
  resources :follows
  
get 'projects/:id/join' => 'projects#join'
get 'projects/:id/follow' => 'projects#follow'

end

app/models/collaborates.rb
class Collaborates < ActiveRecord::Base
	belongs_to :user
	belongs_to :project


end

app/models/comments_on.rb
class CommentsOn < ActiveRecord::Base
	belongs_to :users
	belongs_to :projects
end

app/models/follows.rb
class Follows < ActiveRecord::Base
	belongs_to :users
	belongs_to :projects
end

app/models/has_skills.rb
class HasSkill < ActiveRecord::Base
	belongs_to :users
	belongs_to :skills
end

app/models/has_tags.rb
class HasTags < ActiveRecord::Base
	belongs_to :tags
	belongs_to :projects
end

app/models/is_colleague_of.rb
class IsColleagueOf < ActiveRecord::Base
	belongs_to :users
end

app/models/message.rb
class Message < ActiveRecord::Base
	has_many :sends
	has_many :users, :through => :sends
end

app/models/project.rb
class Project < ActiveRecord::Base

	has_many :tasks
	accepts_nested_attributes_for :tasks,:allow_destroy => true

mount_uploader :propic, PropicUploader


	has_many :comments_on
	has_many :users, :through => :comments_on

	has_many :collaborates
	has_many :users, :through => :collaborates

	has_many :follows
	has_many :users, :through => :follows

	has_many :requires_skill
	has_many :skills, :through => :requires_skill

	has_many :has_tags
	has_many :tags, :through => :has_tags



	 

end

app/models/requires_skills.rb
class RequiresSkill < ActiveRecord::Base
	belongs_to :skills
	belongs_to :projects
end

app/models/sends.rb
class Sends < ActiveRecord::Base
	belongs_to :users
	belongs_to :messages
end

app/models/skill.rb
class Skill < ActiveRecord::Base

	has_many :has_skill
	has_many :users, :through => :has_skill

	has_many :requires_skill
	has_many :projects, :through => :requires_skill
end

app/models/tag.rb
class Tags < ActiveRecord::Base

	has_many :has_tags
	has_many :projects, :through => :has_tags
end

app/models/task.rb
class Task < ActiveRecord::Base

	has_many :works_on
	has_many :users, :through => :works_on

	belongs_to :projects
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


	

	mount_uploader :avatar, AvatarUploader


# app/views/users/_form.html.erb

	def self.search(search)
  		if search
    		self.where('name like ?', "%#{search}%")
  		else
    		self.all
  		end
	end

	has_many :sends
	has_many :messages, :through => :sends

	has_many :is_colleague_of
	has_many :users, :through => :is_colleague_of

	has_many :works_on
	has_many :tasks, :through => :works_on

	has_many :comments_on
	has_many :projects, :through => :comments_on

	has_many :collaborates
	has_many :projects, :through => :collaborates

	has_many :follows
	has_many :projects, :through => :follows

	has_many :has_skill
	has_many :skills, :through => :has_skill


scope :alphasort, lambda { order("users.first_name ASC") }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/models/works_on.rb
class WorksOn < ActiveRecord::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  respond_to :html
  before_action :set_project, only: [:show, :edit, :update, :destroy, :join]
  before_action :set_creator, only: [:show, :edit, :update]
  before_filter :authenticate_user!, :except => [:index, :show]

  def index
    @projects = Project.find_by_sql "SELECT *
    FROM projects;"

    respond_with(@projects)
  end

  def show
    @tasks = Task.find_by_sql "SELECT *
    FROM tasks, works_on
    WHERE tasks.tid=works_on.tid
    AND tasks.project_id="+params[:id].to_s
    respond_with(@project)
  end

  def new
    @project = Project.new
    respond_with(@project)
  end

  def edit
    respond_with(@project)
  end

  def create
    @project = Project.new(project_params)
    flash[:notice] = 'Project was successfully created.' if @project.save
    respond_with(@project)
  end

  def update
    flash[:notice] = 'Project was successfully updated.' if @project.update(project_params)
    respond_with(@project)
  end

  def destroy
    @project= Project.delete_all("id="+params[:id].to_s)
redirect_to action: 'index'
end

  def delete
    @project= Project.delete_all("id="+params[:id].to_s)
    redirect_to "/index"
  end

  def join
  project = Project.find(params[:id])
   @connection = ActiveRecord::Base.connection
    result = @connection.exec_query('INSERT INTO collaborates VALUES('+current_user.id.to_s+','+project.id.to_s+");")
    redirect_to action: 'show'
     
   
end

def follow
  project = Project.find(params[:id])
   @connection = ActiveRecord::Base.connection
    result = @connection.exec_query('INSERT INTO follows VALUES('+current_user.id.to_s+','+project.id.to_s+");")
    redirect_to action: 'show'


  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def set_creator
      @creator = User.find(@project.creator_id)
    end

    def project_params
      params.require(:project).permit(:creator_id, :name, :description,:slogan,:git,:link, :propic, tasks_attributes:[:id, :task_name,:description, :_destroy])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
 
  def index
    @users = User.search(params[:search])
  end

  def show
    @user = User.find(params[:id])
    @projects = Project.find_by_sql "SELECT * FROM projects WHERE creator_id="+params[:id].to_s
    @i_follow = Follows.find_by_sql "SELECT * FROM follows WHERE uid="+params[:id].to_s
    @collaborates = Collaborates.find_by_sql "SELECT * FROM collaborates WHERE user_id="+params[:id].to_s
    @following_me = Follows.find_by_sql "SELECT * FROM follows, projects WHERE follows.pid=projects.id AND creator_id="+params[:id].to_s
  end

  def edit
  	@user = User.find(params[:id])
  end

  def new
    @user = User.new
    
  end


 def update 

    account_update_params = devise_parameter_sanitizer.sanitize(:account_update)
    # For Rails 3
    # account_update_params = params[:user]

    # required for settings form to submit when password is left blank
    if account_update_params[:password].blank?
      account_update_params.delete("password")
      account_update_params.delete("password_confirmation")
    end


  @user = User.find( params[:id])
  if @user.update_attributes(account_update_params)
    sign_in @user, :bypass => true
    respond_with(@user)
  else
    render('edit')
  end
end

private
  
  def user_params
    params.require(:user).permit(:name, :last_name, :email, :website, :facebook, :twitter, :linkedin, :github, :location, :interest, :work_in, :info, :avatar )
  end
  

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav id="navbar" class="navbar navbar-default navbar-fixed-top">
<script type="text/javascript">
    try{ace.settings.check('navbar' , 'fixed')}catch(e){}
  </script>
  <div class="navbar-container" id="navbar-container">

  <!-- Toggler button when mobile -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'TechStorm', root_path, class: 'navbar-brand' %>
    </div>


    <div class="collapse navbar-collapse pull-left" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Projects', projects_path %></li>
        <li><%= link_to 'Users', users_path %></li>
      </ul>
    </div>


    <div class="collapse navbar-collapse pull-right">
      <ul class="nav navbar-nav  navbar-left">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>   


  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<% if user_signed_in? %>

<div class="navbar-buttons navbar-header pull-right visible-desktop visible-tablet hidden-phone" role="navigation">
	<ul class="nav ace-nav">
		<li class="green"> <!--Class changes from grey to grey-open-->
			<a data-toggle="dropdown" class="dropdown-toggle" href="#">
				<i class="fa fa-plus"></i>
			</a>
			<ul class="dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">

				<li class="dropdown-footer">
						
						<i class="ace-icon fa fa-arrow-right"><%= link_to 'New Project', new_project_path %></i>
				</li>
			</ul>
		</li>


		<!--Grey button-->
		<li class="grey"> <!--Class changes from grey to grey-open-->
			<a data-toggle="dropdown" class="dropdown-toggle" href="#">
				<i class="ace-icon fa fa-tasks"></i>

			</a>
			<ul class="dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
			To implement
				<!-- <li class="dropdown-header">
					<i class="ace-icon fa fa-check"></i>
					4 Tasks to complete
				</li>

				<li>
					<a href="#"> 
						<div class="clearfix"> 
							<span class="pull-left">Task Name</span>
							<span class="pull-right">65%</span>
						</div>

						<div class="progress progress-mini">
							<div style="width:65%" class="progress-bar"></div>
						</div>
					</a>
				</li>

				<li class="dropdown-footer">
					<a href="#">
						See tasks with details
						<i class="ace-icon fa fa-arrow-right"></i>
					</a>
				</li> -->
			</ul>
		</li>

		<!--Purple button-->
		<li class="purple">
			<a data-toggle="dropdown" class="dropdown-toggle" href="#">
				<i class="ace-icon fa fa-bell"></i>
			</a>
			<ul class="dropdown-menu-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-close">
			To implement
				<!-- <li class="dropdown-header">
					<i class="ace-icon fa fa-exclamation-triangle"></i>
					8 Notifications
				</li>

				<li>
					<a href="#">
						<div class="clearfix">
							<span class="pull-left">
								<i class="btn btn-xs no-hover btn-pink fa fa-comment"></i>
								New Comments
							</span>
							<span class="pull-right badge badge-info">+12</span>
						</div>
					</a>
				</li>

				<li class="dropdown-footer">
					<a href="#">
						See all notifications
						<i class="ace-icon fa fa-arrow-right"></i>
					</a>
				</li> -->
			</ul>
		</li>

		<li class="green">
			<a data-toggle="dropdown" class="dropdown-toggle" href="#">
				<i class="ace-icon fa fa-envelope"></i>

			</a>

			<ul class="dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
				To implement
				<!-- <li class="dropdown-header">
					<i class="ace-icon fa fa-envelope-o"></i>
					5 Messages
				</li>

				<li class="dropdown-content">
					<ul class="dropdown-menu dropdown-navbar">
						<li>
							<a href="#">
								<img src="../assets/avatars/avatar.png" class="msg-photo" alt="Alex's Avatar" />
								<span class="msg-body">
									<span class="msg-title">
										<span class="blue">Alex:</span>
										Message Summary
									</span>

									<span class="msg-time">
										<i class="ace-icon fa fa-clock-o"></i>
										<span>Message Time</span>
									</span>
								</span>
							</a>
						</li>
					</ul>
				</li>

				<li class="dropdown-footer">
					<a href="inbox.html">
						See all messages
						<i class="ace-icon fa fa-arrow-right"></i>
					</a>
				</li> -->
			</ul>
		</li>

		<!-- USER BUTTON -->
		<li class="light-blue">
			<a data-toggle="dropdown" href="#" class="dropdown-toggle">
				<span class="user-info">
					<small>Welcome,</small>
					<%= current_user.name %>
				</span>

				<i class="ace-icon fa fa-caret-down"></i>
			</a>

			<!--USER DROPDOWN LIST-->
			<ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-closer">
				<li><%= link_to 'Edit my account', edit_user_registration_path %></li>
				<li class="divider"></li>	
				<li><%= link_to 'View my account', current_user %></li>
				<li class="divider"></li>
				<li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
				

			</ul>
		</li>
	</ul>
</div>

<% else %>
<div class="navbar-buttons navbar-header pull-right" role="navigation">
					<ul class="nav ace-nav">
						<li class="green">
							<a data-toggle="dropdown" class="dropdown-toggle" href="#">
								Log In
								<span class="badge badge-gray"></span>
							</a>

							<ul class="dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
								<li class="dropdown-content">
									<ul class="dropdown-menu dropdown-navbar">
										<%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => { :role => 'form'}) do |f| %>
										<li class="input-lg">
											<%= f.text_field :email, :placeholder => "email" %>
											<br></br>
										</li>

										<li class="input-lg">
											<%= f.password_field :password, :placeholder => "password" %>
										</li>

										<li class="input-sm">
											<%= f.check_box :remember_me %> Remember Me
										</li>

										<li class="input-sm">
											<%= link_to "Forgot your password?", new_password_path(:user) %>
										</li>
									</ul>
								</li>

								<li class="dropdown-footer input-sm">
									<%= f.submit 'Sign in' %>
								</li>
								<% end %>
							</ul>
						</li>
					</ul>
				</div>
			</div><!-- /.navbar-container -->
		</div> <!-- /.navbar-default -->

<script type="text/javascript">
	$('.dropdown-menu input').click(function(e) {
        e.stopPropagation(); //This will prevent the event from bubbling up and close the dropdown when you type/click on text boxes.
    });
</script>


<% end %>

app/views/layouts/_side_bar.html.erb
<script type="text/javascript">
      try{ace.settings.check('main-container' , 'fixed')}catch(e){}
    </script>

    <div id="sidebar" class="hidden-md hidden-lg visible-phone sidebar responsive">
      <script type="text/javascript">
        try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
      </script>




      <ul class="nav nav-list">

      <% unless user_signed_in? %>
      	<li class="active">
      		<a href="#" class="dropdown-toggle">
      			<i class="fa fa-power-off"></i>
      			<span class="menu-text">
      				Log In
      			</span>
      			<b class="arrow fa fa-angle-down"></b>
      		</a>
      		<b class="arrow"></b>

      		<ul class="submenu">
      			<%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => { :role => 'form'}) do |f| %>
      			<li class="input-sm">
      				<%= f.text_field :email, :placeholder => "email" %>
      				<b class="arrow"></b>
      			</li>

      			<li class="input-sm">
      				<%= f.password_field :password, :placeholder => "password" %>
      				<b class="arrow"></b>
      			</li>
      			<li class="input-sm">
      				<%= f.check_box :remember_me %> Remember Me
      				<b class="arrow"></b>
      			</li>
      			<li class="input-sm">
      				<%= link_to "Forgot your password?", new_password_path(:user) %>
      				<b class="arrow"></b>
      			</li>
      			<li class="input-sm">
      				<%= f.submit 'Sign in' %>
      				<b class="arrow"></b>
      			</li>
      			<% end %>
      		</ul>
      	</li>


      	<% else %>
      	<li class="">
      		
      		<a href="/projects">
			<i class="menu-icon fa fa-cubes"></i>
      		<span class="menu-text">Projects</span>
      		</a>
      		<b class="arrow"></b>
      	</li>

      	<li class="">
      		<a href="/users">
			<i class="menu-icon fa fa-users"></i>
      		<span class="menu-text">Users</span>
      		</a>
      		<b class="arrow"></b>
      	</li>

      	<li class="">
      		<a href="/projects/new">
			<i class="menu-icon fa fa-plus"></i>
      		<span class="menu-text">New Project</span>
      		</a>
      		<b class="arrow"></b>
      	</li>



      	<li class="">
      		<a href="#" class="dropdown-toggle">
      			<i class="menu-icon fa fa-user"></i>
      			<span class="menu-text">
      				Me
      			</span>
      			<b class="arrow fa fa-angle-down"></b>
      		</a>
      		<b class="arrow"></b>

      		<ul class="submenu">
      			<li class="">
      					<li class="dropdown-toggle"><%= link_to 'View my account', current_user %></li>
      			</li>
      			<li class="">
      					<li class="dropdown-toggle"><%= link_to 'Edit my account', edit_user_registration_path %></li>

      			</li>
      		</ul>
      	</li>


		<li class="">
      		<a href="/users/sign_out" data-method="delete">
			<i class="menu-icon fa fa-power-off"></i>
      		<span class="menu-text">Sign Out</span>
      		</a>
      		<b class="arrow"></b>
      	</li>
      	<% end %>
      	
      </ul><!-- /.nav-list -->

        <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
          <i class="ace-icon fa fa-angle-double-left" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
        </div>

        <script type="text/javascript">
          try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
        </script>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "myapp" %></title>
  <%= csrf_meta_tags %>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!-- bootstrap & fontawesome -->
  <link rel="stylesheet" type="text/css" href= "../../assets/stylesheets/main.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" href="../../assets/stylesheets/ace-fonts.css" />
  <link rel="stylesheet" href="../../assets/stylesheets/ace.min.css" id="main-ace-style" />
  <!--[if lte IE 9]><link rel="stylesheet" href="../../assets/stylesheets/ace-part2.min.css" /><![endif]-->
  <link rel="stylesheet" href="../../assets/stylesheets/ace-skins.min.css" />
  <link rel="stylesheet" href="../../assets/stylesheets/ace-rtl.min.css" />
  
  <!--[if lte IE 9]><link rel="stylesheet" href="../../assets/stylesheets/ace-ie.min.css" /><![endif]-->
  

</head>
<body class="no-skin">

  <%= render 'layouts/navigation' %>

  <div class="main-container" id="main-container">
    
  <%= render 'layouts/side_bar' %>
  <%= render 'layouts/messages' %>
  <%= yield %>

  </div>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!--[if !IE]> -->
    <script type="text/javascript">
    window.jQuery || document.write("<script src='../../assets/javascripts/jquery.min.js'>"+"<"+"/script>");
    </script>
    <!-- <![endif]-->

<!--[if IE]>
<script type="text/javascript">
 window.jQuery || document.write("<script src='../../assets/javascripts/jquery1x.min.js'>"+"<"+"/script>");
</script>
<![endif]-->

<script type="text/javascript">
if('ontouchstart' in document.documentElement) document.write("<script src='..assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
</script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="../../assets/javascripts/bootstrap.min.js"></script>
<script src="../../assets/javascripts/ace-elements.min.js"></script>
<script src="../../assets/javascripts/ace.min.js"></script>
<script src="../../assets/javascripts/ace-extra.min.js"></script>

<!--[if lte IE 8]>
<script src="../../assets/javascripts/html5shiv.min.js"></script>
<script src="../../assets/javascripts/respond.min.js"></script>
<![endif]-->

<link rel="stylesheet" href="../../assets/stylesheets/ace.onpage-help.css" />
<link rel="stylesheet" href="../../assets/javascripts/sunburst.css" />


</body>
</html>